config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  ##resources :photos, only: [:create, :destroy]
  
  post 'articles/upload'
  get 'articles/download'

  resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :comments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
#  belongs_to :user_id
#  belongs_to :photo_id

  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user

  validates :user_id, presence: true
  ##validates :content, presence: true, length: { maximum: 255 }

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }  
  has_secure_password
  
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index

  end

  def show

  end

  def new
    @comment = Comment.new
  end

  def create
    binding.pry
    @comment = current_user.comments.build(comment_params)
    @photo = @comment.photo
    if @comment.save
      flash[:success] = "コメントが投稿されました。"
      redirect_to @photo
    else
      @comments = @photo.comments
      flash.now[:danger] = "コメントが投稿されませんでした。。"
      render 'photo/show'
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    #binding.pry
    @comment.destroy
    flash[:success] = 'コメントを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :photo_id)
  end

  def correct_user
    @photo = current_user.photo.find_by(id: params[:id])
    unless @photo
      redirect_to root_url
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index

  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new(photo_id: @photo.id)
    @comments = @photo.comments
  end

  def new
    @user = current_user
    @photo = Photo.new
    @comment = Comment.new
  end

  def create
    @photo = current_user.photos.build(photo_params)
    if @photo.save    
      flash[:success] = '写真 が正常に投稿されました'
      redirect_to @photo
    else
      @user = current_user
      flash.now[:danger] = '写真 が投稿されませんでした'
      render :new
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    #binding.pry
    @photo.destroy

    flash[:success] = '写真 は正常に削除されました'
    redirect_to root_url    
  end
  
  private

  def photo_params
    params.require(:photo).permit(:user_id, :image, :image_cache, :remove_image)
  end

  def correct_user
    @photo = current_user.photo.find_by(id: params[:id])
    unless @photo
      redirect_to root_url
    end
  end

  def comment_params
    params.require(:photo).permit(:content, :photo_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @photo = current_user.photos.build  # form_for 用
      @photos = current_user.photos.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">投稿写真一覧</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PhotoList</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <% if @photo.image? %>
      <div class="thumbnail">
      <%= image_tag @photo.image.url %>
    </div>
  <% end %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @photo.persisted? && @photo.image? %>
      <label>
      <%= f.check_box :remove_image %>
      画像を削除
    </label>
  <% end %>
  </div>

  <div class="actions">
    <%= f.submit '投稿', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/photos/_photos.html.erb
<ul class="media-list">
  <% photos.each do |photo| %>
    <%= link_to "show", photo %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(photo.user, { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to photo.user.name, user_path(photo.user) %> <span class="text-muted">posted at <%= photo.created_at %></span>
        </div>
        <div>
          <p><%= photo.content %></p>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate photos %>
</ul>

app/views/photos/new.html.erb
<h1>新規写真投稿ページ</h1>

<%= render 'form', photo: @photo , user: @user , comment: @comment %>

app/views/photos/show.html.erb
<p>
  <strong>Image: </strong>
  <%= @photo.id %>
  <% if @photo.image? %>
    <div class="thumbnail">
    <%= image_tag @photo.image.url %>
  </div>
  <% end %>
</p>

<%= form_for(@comment) do |f| %>
  <%= f.hidden_field :photo_id %> 
  <%= f.text_area :content %>
  <%= f.submit 'コメントする', class: 'btn btn-primary' %>
<% end %>

<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.content %></li>
    <%= link_to "Delete",  comment, method: :delete,  class: 'btn btn-danger btn-xs' %>
  <% end %>
</ul>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <% @photos.each do |photo| %>
    <%= link_to(photo) do %>
      <%= photo.id %>
      <%= image_tag photo.image.try!(:thumb) %>
      <%= link_to "Delete",  photo, method: :delete,  class: 'btn btn-danger btn-xs' %>
    <% end %>
  <% end %>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the PhotoList</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <% if current_user == @user %>
        <li><a href="#"><%= link_to '新しい写真の投稿', new_photo_path, class: "btn btn-primary" %></a></li>
        <li><a href="#"><%= link_to '投稿写真一覧', root_path, class: "btn btn-primary" %></a></li>
      <% end %>
    </ul>
  </div>
</div>